### create a new provider
POST http://localhost:5000/providers
Content-Type: application/json

{
    "name" : "Trisha Lewis",
    "group": "Group A",
    "brighttreeId": 4
}

### Update an existing provider
PATCH  http://localhost:5000/providers/1
Content-Type: application/json

{
    "id": 3,
    "name" : "Grant Dolin",
    "group": "Group A",
    "brighttreeId": 2
}

### Get all providers
GET http://localhost:5000/providers
Content-Type: application/json
